site_name: Graphchain Documentation
site_url: https://graphchain.org/docs # Update this to match your site structure
docs_dir: docs                   # Source Markdown files location
site_dir: site/docs                   # Build output location

theme:
  name: material                      # Optional, use MkDocs Material theme
  favicon: '../img/favicon.svg'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API:
      - Overview: api/overview.md
      - Endpoints: api/endpoints.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
  - mermaid2:
      version: 10.0.2