site_name: Graphchain Documentation
site_url: https://graphchain.org/docs/    
docs_dir: docs                            # Source Markdown files location
site_dir: ../site/docs                    # Build output location

theme:
  name: material                      
  favicon: 'img/favicon3.svg'
  logo: 'img/favicon3.svg' 
  palette:
    primary: 'black'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Validators: validators.md
  - Tokens: tokens.md
  - Testnet: testnet.md
  - Mainnet: mainnet.md
  - Governance: governance.md
  - Wallets: wallets.md
  - Roadmap: roadmap.md
  - Resources: resources.md
  - FAQ: faq.md


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
