site_name: Graphchain Documentation
site_url: https://graphchain.org/docs # Update this to match your site structure
docs_dir: docs                   # Source Markdown files location
site_dir: site/docs                   # Build output location

theme:
  name: material                      # Optional, use MkDocs Material theme
  favicon: '../img/favicon.svg'
  logo: '../img/favicon.svg' 
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
