site_name: Graphchain Documentation
site_url: https://graphchain.org/docs # Update this to match your site structure
docs_dir: docs                   # Source Markdown files location
site_dir: ../site/docs              # Build output location

theme:
  name: material                      # Optional, use MkDocs Material theme
  favicon: 'img/favicon3.svg'
  logo: 'img/favicon3.svg' 
  palette:
    primary: 'black'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Testnet: testnet.md
  - Mainnet: mainnet.md
  - Validators: validators.md
  - Governance: governance.md
  - Wallets: wallets.md
  - Roadmap: roadmap.md
  - Resources: resources.md
  - Tokens: tokens.md
  - FAQ: faq.md


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
